admin_formation:
    resource: "@AdminFormationBundle/Resources/config/routing.yml"
    prefix:   /
admin_formation_service_new:
    path:     /new-service
    defaults: { _controller: AdminFormationBundle:Service:new }
sous_service_new:
    path:     /new-sous-service
    defaults: { _controller: AdminFormationBundle:sous_Service:new }
    methods:  [GET, POST]
formateur_new:
        path:     /new-formateur
        defaults: { _controller: "AdminFormationBundle:Formateur:new" }
        methods:  [GET, POST]
formation_new:
        path:     /new-formation
        defaults: { _controller: "AdminFormationBundle:Formation:new" }
        methods:  [GET, POST]
fos_user:
    resource:    '@FOSUserBundle/Resources/config/routing/all.xml'
fos_user_profile:
    resource:    "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:    /profile
fos_user_profile_edit:
    resource:    "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:    /profile/edit
app:
    resource:    '@AppBundle/Controller/'
    type:    annotation
