<?php

namespace Admin\FormationBundle\Repository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends \Doctrine\ORM\EntityRepository
{
    public  function findFormationsBynom($motcle)
    {

        $query=$this->createQueryBuilder('f')
            ->where('f.nomFormation LIKE :nomFormation')
            ->orWhere('f.descriptionFormation LIKE :descriptionFormation')
            ->setParameter('nomFormation', '%'.$motcle.'%')
            ->setParameter('descriptionFormation', '%'.$motcle.'%')
            ->orderBy('f.nomFormation', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
