<?php

namespace Admin\FormationBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public  function findServiceBynom($motcle)
    {

        $query=$this->createQueryBuilder('f')
            ->where('f.libelleService LIKE :libelleService')
            ->orWhere('f.descriptionService LIKE :descriptionService')
            ->setParameter('libelleService', '%'.$motcle.'%')
            ->setParameter('descriptionService', '%'.$motcle.'%')
            ->orderBy('f.libelleService', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
