<?php

namespace Admin\FormationBundle\Repository;

/**
 * sous_ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sous_ServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
