<?php

namespace Admin\FormationBundle\Repository;

/**
 * sous_ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sous_ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public  function findSousServiceBynom($motcle)
    {

        $query=$this->createQueryBuilder('f')
            ->where('f.libelleSous LIKE :libelleSous')
            ->orWhere('f.descriptionSous LIKE :descriptionSous')
            ->setParameter('libelleSous', '%'.$motcle.'%')
            ->setParameter('descriptionSous', '%'.$motcle.'%')
            ->orderBy('f.libelleSous', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
