formation_index:
    path:     /
    defaults: { _controller: "AdminFormationBundle:Formation:index" }
    methods:  GET

formation_show:
    path:     /{id}/show
    defaults: { _controller: "AdminFormationBundle:Formation:show" }
    methods:  GET

formation_new:
    path:     /new
    defaults: { _controller: "AdminFormationBundle:Formation:new" }
    methods:  [GET, POST]

formation_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminFormationBundle:Formation:edit" }
    methods:  [GET, POST]

formation_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminFormationBundle:Formation:delete" }
    methods:  DELETE
formation_recherche:
    path:     /recherche
    defaults: { _controller: "AdminFormationBundle:Formation:recherche" }
