formateur_index:
    path:     /
    defaults: { _controller: "AdminFormationBundle:Formateur:index" }
    methods:  GET

formateur_show:
    path:     /{id}/show
    defaults: { _controller: "AdminFormationBundle:Formateur:show" }
    methods:  GET

formateur_new:
    path:     /new
    defaults: { _controller: "AdminFormationBundle:Formateur:new" }
    methods:  [GET, POST]

formateur_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminFormationBundle:Formateur:edit" }
    methods:  [GET, POST]

formateur_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminFormationBundle:Formateur:delete" }
    methods:  [GET, POST]
