service_index:
    path:     /
    defaults: { _controller: "AdminFormationBundle:Service:index" }
    methods:  GET

service_show:
    path:     /{id}/show
    defaults: { _controller: "AdminFormationBundle:Service:show" }
    methods:  GET

service_new:
    path:     /new
    defaults: { _controller: "AdminFormationBundle:Service:new" }
    methods:  [GET, POST]

service_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminFormationBundle:Service:edit" }
    methods:  [GET, POST]

service_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminFormationBundle:Service:delete" }
    methods:  DELETE
service_recherche:
    path:     /recherche
    defaults: { _controller: "AdminFormationBundle:Service:recherche" }